trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Authenticate with Azure Artifacts feed
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'MyMavenFeed'

# 2. Build & deploy using the authenticated settings.xml
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    options: '-s $(MAVEN_SETTINGS_XML)'
    publishJUnitResults: false

