# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: default   # your self-hosted agent pool

steps:
# 1. Authenticate to Azure Artifacts feed
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'MyMavenFeed'

# 2. Build and deploy with Maven
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'deploy'
    options: '-s $(MAVEN_SETTINGS_XML)'
    publishJUnitResults: false
